/**
 * DeepAstro QA Golden Test Fixtures
 * 13 controlled adversarial fixtures for testing Observatory V2.0,
 * Challenger Engine, Falsifiability, AI Critic Mesh, and Hallucination Auditor.
 *
 * INVARIANT: Every fixture is strictly marked dataset_type = "SYNTHETIC_TEST"
 * and CANNOT contribute to real-world production accuracy metrics.
 */

export interface QAGoldenFixture {
  id: string;
  category: string;
  label: string;
  dataset_type: 'SYNTHETIC_TEST';
  forecastText: string;
  claim: string;
  domain: string;
  confidence: number;
  timeWindowStart: string;
  timeWindowEnd: string;
  evidenceCount: number;
  contradictionCount: number;
  expectedOutcome: string;
  expectedRecommendation: 'PASS' | 'SOFTEN' | 'REQUEST_CONTEXT' | 'SUPPRESS';
  planetarySignals: string[];
  notes: string;
}

export const QA_GOLDEN_FIXTURES: QAGoldenFixture[] = [
  {
    id: 'GOLDEN_01_HIGH_EVIDENCE',
    category: 'HIGH_EVIDENCE',
    label: 'QA TEST DATA - High Evidence Specific Prediction',
    dataset_type: 'SYNTHETIC_TEST',
    forecastText: 'Career promotion in technology sector during Saturn-Jupiter transit period in Q3 2027.',
    claim: 'Promotion to leadership in technology',
    domain: 'CAREER',
    confidence: 0.74,
    timeWindowStart: '2027-07-01',
    timeWindowEnd: '2027-09-30',
    evidenceCount: 5,
    contradictionCount: 0,
    expectedOutcome: 'CONFIRMED',
    expectedRecommendation: 'PASS',
    planetarySignals: ['10th Lord in 11th House', 'Saturn transit 10th house', 'Jupiter trine Sun', 'Mahadasha Jupiter', 'Antardasha Mars'],
    notes: 'Well-specified time window, specific domain, robust multi-signal backing.',
  },
  {
    id: 'GOLDEN_02_LOW_EVIDENCE',
    category: 'LOW_EVIDENCE',
    label: 'QA TEST DATA - Low Evidence Claim',
    dataset_type: 'SYNTHETIC_TEST',
    forecastText: 'Major career shift will occur within 6 months.',
    claim: 'Sudden career transition',
    domain: 'CAREER',
    confidence: 0.60,
    timeWindowStart: '2027-01-01',
    timeWindowEnd: '2027-06-30',
    evidenceCount: 0,
    contradictionCount: 0,
    expectedOutcome: 'UNKNOWN',
    expectedRecommendation: 'SUPPRESS',
    planetarySignals: [],
    notes: 'Zero planetary evidence supporting claim -> Should be suppressed or softened.',
  },
  {
    id: 'GOLDEN_03_CONTRADICTORY',
    category: 'CONTRADICTORY',
    label: 'QA TEST DATA - High Contradiction Signals',
    dataset_type: 'SYNTHETIC_TEST',
    forecastText: 'Significant financial windfall from unexpected legacy inheritance.',
    claim: 'Financial gain via legacy',
    domain: 'FINANCE',
    confidence: 0.78,
    timeWindowStart: '2027-03-01',
    timeWindowEnd: '2027-05-31',
    evidenceCount: 1,
    contradictionCount: 4,
    expectedOutcome: 'CONTRADICTED',
    expectedRecommendation: 'SUPPRESS',
    planetarySignals: ['8th Lord afflicted by Rahu', '12th Lord in 2nd house', 'Debilitated Jupiter', 'Loss transit active'],
    notes: 'Heavy contradictory signals outweigh supporting evidence -> Strict SUPPRESS.',
  },
  {
    id: 'GOLDEN_04_VAGUE',
    category: 'VAGUE',
    label: 'QA TEST DATA - Universal Barnum Statement',
    dataset_type: 'SYNTHETIC_TEST',
    forecastText: 'Something important is coming. Life will improve and opportunities await.',
    claim: 'General life improvement',
    domain: 'GENERAL',
    confidence: 0.90,
    timeWindowStart: '2027-01-01',
    timeWindowEnd: '2027-12-31',
    evidenceCount: 1,
    contradictionCount: 0,
    expectedOutcome: 'UNKNOWN',
    expectedRecommendation: 'SUPPRESS',
    planetarySignals: ['Sun in Aries'],
    notes: 'Contains multiple Barnum phrases with universal applicability -> Suppressed.',
  },
  {
    id: 'GOLDEN_05_NON_FALSIFIABLE',
    category: 'NON_FALSIFIABLE',
    label: 'QA TEST DATA - Non-Falsifiable Tautology',
    dataset_type: 'SYNTHETIC_TEST',
    forecastText: 'You may or may not experience spiritual evolution at some point in your life.',
    claim: 'Spiritual evolution',
    domain: 'SPIRITUALITY',
    confidence: 0.50,
    timeWindowStart: '',
    timeWindowEnd: '',
    evidenceCount: 0,
    contradictionCount: 0,
    expectedOutcome: 'UNKNOWN',
    expectedRecommendation: 'REQUEST_CONTEXT',
    planetarySignals: [],
    notes: 'Missing time window and non-falsifiable directional outcome.',
  },
  {
    id: 'GOLDEN_06_OVERCONFIDENT',
    category: 'OVERCONFIDENT',
    label: 'QA TEST DATA - Overconfident Language',
    dataset_type: 'SYNTHETIC_TEST',
    forecastText: 'You will 100% definitely achieve guaranteed wealth beyond doubt.',
    claim: 'Guaranteed wealth',
    domain: 'FINANCE',
    confidence: 0.99,
    timeWindowStart: '2027-01-01',
    timeWindowEnd: '2027-06-30',
    evidenceCount: 2,
    contradictionCount: 0,
    expectedOutcome: 'PARTIAL',
    expectedRecommendation: 'SOFTEN',
    planetarySignals: ['Venus in 2nd house'],
    notes: 'Deterministic claim violating epistemic boundaries -> Downscaled and softened.',
  },
  {
    id: 'GOLDEN_07_HALLUCINATED',
    category: 'HALLUCINATED',
    label: 'QA TEST DATA - Model Hallucination of Astronomy',
    dataset_type: 'SYNTHETIC_TEST',
    forecastText: 'Jupiter creates a quintile aspect to Ketu in the 13th house according to Brihat Parashara verse 9999.',
    claim: 'Invented astrological placement',
    domain: 'ASTRONOMY',
    confidence: 0.85,
    timeWindowStart: '2027-01-01',
    timeWindowEnd: '2027-06-30',
    evidenceCount: 0,
    contradictionCount: 2,
    expectedOutcome: 'CONTRADICTED',
    expectedRecommendation: 'SUPPRESS',
    planetarySignals: ['Non-existent 13th house'],
    notes: 'Hallucination Auditor triggers CRITICAL on 13th house and fake verse citation.',
  },
  {
    id: 'GOLDEN_08_TEMPORAL_LEAKAGE',
    category: 'TEMPORAL_LEAKAGE',
    label: 'QA TEST DATA - Future Temporal Leakage Injection',
    dataset_type: 'SYNTHETIC_TEST',
    forecastText: 'Historical backtest for 2024 using data generated in 2026.',
    claim: 'Backtest validity',
    domain: 'CALIBRATION',
    confidence: 0.80,
    timeWindowStart: '2024-01-01',
    timeWindowEnd: '2024-12-31',
    evidenceCount: 1,
    contradictionCount: 0,
    expectedOutcome: 'CONTRADICTED',
    expectedRecommendation: 'SUPPRESS',
    planetarySignals: [],
    notes: 'Temporal Leakage Red Team flags future snapshot timestamp.',
  },
  {
    id: 'GOLDEN_09_PARTIAL_OUTCOME',
    category: 'PARTIAL_OUTCOME',
    label: 'QA TEST DATA - Partial Outcome Match',
    dataset_type: 'SYNTHETIC_TEST',
    forecastText: 'Relocation to foreign country for education in autumn 2027.',
    claim: 'Foreign education relocation',
    domain: 'EDUCATION',
    confidence: 0.70,
    timeWindowStart: '2027-09-01',
    timeWindowEnd: '2027-11-30',
    evidenceCount: 3,
    contradictionCount: 0,
    expectedOutcome: 'PARTIAL',
    expectedRecommendation: 'PASS',
    planetarySignals: ['9th lord in 12th house', 'Jupiter aspect 9th'],
    notes: 'Outcome occurred partially (remote international program rather than physical relocation).',
  },
  {
    id: 'GOLDEN_10_UNKNOWN_OUTCOME',
    category: 'UNKNOWN_OUTCOME',
    label: 'QA TEST DATA - Unconfirmed Outcome (Silence)',
    dataset_type: 'SYNTHETIC_TEST',
    forecastText: 'New creative hobby or musical interest initiated in early 2027.',
    claim: 'Creative musical pursuit',
    domain: 'CREATIVITY',
    confidence: 0.65,
    timeWindowStart: '2027-01-01',
    timeWindowEnd: '2027-03-31',
    evidenceCount: 2,
    contradictionCount: 0,
    expectedOutcome: 'UNKNOWN',
    expectedRecommendation: 'PASS',
    planetarySignals: ['Venus in 5th house'],
    notes: 'No user feedback recorded -> Strictly classified as UNKNOWN, never confirmation.',
  },
  {
    id: 'GOLDEN_11_MODEL_DISAGREEMENT',
    category: 'MODEL_DISAGREEMENT',
    label: 'QA TEST DATA - Multi-Provider Disagreement',
    dataset_type: 'SYNTHETIC_TEST',
    forecastText: 'Controversial career turning point with divergent model interpretations.',
    claim: 'Major career fork',
    domain: 'CAREER',
    confidence: 0.55,
    timeWindowStart: '2027-04-01',
    timeWindowEnd: '2027-08-31',
    evidenceCount: 2,
    contradictionCount: 2,
    expectedOutcome: 'UNKNOWN',
    expectedRecommendation: 'SOFTEN',
    planetarySignals: ['Saturn-Rahu conjunction'],
    notes: 'Z53 predicts growth, OpenAI predicts consolidation -> Epistemic uncertainty surfaced.',
  },
  {
    id: 'GOLDEN_12_DUPLICATE',
    category: 'DUPLICATE',
    label: 'QA TEST DATA - Duplicate Prediction in Same Window',
    dataset_type: 'SYNTHETIC_TEST',
    forecastText: 'Career promotion in IT sector during Q3 2027.',
    claim: 'Promotion to IT leadership',
    domain: 'CAREER',
    confidence: 0.75,
    timeWindowStart: '2027-07-01',
    timeWindowEnd: '2027-09-30',
    evidenceCount: 4,
    contradictionCount: 0,
    expectedOutcome: 'CONFIRMED',
    expectedRecommendation: 'PASS',
    planetarySignals: ['10th Lord strong'],
    notes: 'Duplicate of GOLDEN_01 -> DeduplicationEngine must flag to prevent double counting.',
  },
  {
    id: 'GOLDEN_13_POST_HOC',
    category: 'POST_HOC',
    label: 'QA TEST DATA - Retrospective Post-Hoc Explanation',
    dataset_type: 'SYNTHETIC_TEST',
    forecastText: 'Vague shift in relationships.',
    claim: 'Relationship change',
    domain: 'RELATIONSHIPS',
    confidence: 0.50,
    timeWindowStart: '2027-01-01',
    timeWindowEnd: '2027-06-30',
    evidenceCount: 1,
    contradictionCount: 0,
    expectedOutcome: 'CONTRADICTED',
    expectedRecommendation: 'SUPPRESS',
    planetarySignals: ['Venus aspect'],
    notes: 'Post-outcome note tries to claim event was inevitable -> Excluded from accuracy.',
  },
];
