/**
 * DeepAstro Observatory V2.0 - Extended Types
 * V2 type system for adversarial validation layer.
 */

export type StatementClass = "FACT" | "CALCULATION" | "TRADITIONAL_INTERPRETATION" | "AI_INFERENCE" | "SPECULATION" | "OVERCONFIDENT" | "UNKNOWN";
export interface ClassifiedStatement { statementId: string; text: string; classification: StatementClass; confidence: number; justification: string; requiresEvidence: boolean; }
export type FalsifiabilityLevel = "YES" | "PARTIAL" | "NO";
export interface FalsifiabilityResult { predictionId: string; level: FalsifiabilityLevel; hasDomain: boolean; hasEvent: boolean; hasDirection: boolean; hasTimeWindow: boolean; hasMagnitude: boolean; hasContext: boolean; missingComponents: string[]; reason: string; score: number; }
export type ChallengeRecommendation = "PASS" | "SOFTEN" | "REQUEST_CONTEXT" | "SUPPRESS";
export type BiasFlagType = "BARNUM_STATEMENT" | "CONFIRMATION_BIAS" | "POST_HOC_REASONING" | "TEXAS_SHARPSHOOTER" | "UNIVERSAL_APPLICABILITY" | "OVERCONFIDENCE" | "HINDSIGHT_BIAS" | "ANCHORING" | "SELECTION_BIAS" | "AVAILABILITY_BIAS";
export interface PredictionChallengeResult { predictionId: string; challengedAt: string; strengths: string[]; weaknesses: string[]; supportingEvidence: string[]; contradictoryEvidence: string[]; assumptions: string[]; alternativeInterpretations: string[]; falsificationConditions: string[]; biasFlags: BiasFlagType[]; testabilityScore: number; confidenceCritique: string; recommendation: ChallengeRecommendation; overallRisk: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"; }
export type CriticRole = "EVIDENCE_AUDITOR" | "CONTRADICTION_HUNTER" | "HALLUCINATION_DETECTOR" | "CONFIDENCE_AUDITOR" | "BIAS_BARNUM_DETECTOR" | "TEMPORAL_LEAKAGE_AUDITOR" | "FALSIFIABILITY_AUDITOR";
export interface CriticFinding { criticId: string; role: CriticRole; provider: "Z53" | "OPENAI" | "GEMINI" | "GROK" | "DETERMINISTIC"; findings: string[]; severity: "INFO" | "WARNING" | "HIGH" | "CRITICAL"; flaggedItems: string[]; recommendation: ChallengeRecommendation; latencyMs: number; generatedAt: string; }
export interface CriticMeshResult { predictionId: string; critics: CriticFinding[]; fusedRecommendation: ChallengeRecommendation; consensusConfidenceAdjustment: number; majorDisagreements: string[]; criticalFlags: string[]; generatedAt: string; }
export interface PredictionQualityVector { predictionId: string; evidence_quality: number; testability: number; timing_precision: number; event_specificity: number; context_specificity: number; confidence_calibration: number; contradiction_level: number; unsupported_claim_risk: number; hallucination_risk: number; bias_risk: number; falsifiability: number; model_agreement: number; calculation_integrity: number; temporal_integrity: number; computedAt: string; notes: string[]; }
export type BaselineModel = "BASELINE_RANDOM" | "BASELINE_ALWAYS_UNKNOWN" | "BASELINE_DOMAIN_PRIOR" | "BASELINE_SIMPLE_TIMING" | "DETERMINISTIC_FLOOR";
export interface BaselineResult { model: BaselineModel; eventAccuracy: number; timingAccuracy: number; brierScore: number; coverage: number; notes: string; }
export interface BaselineComparisonResult { deepAstroBrierScore: number; deepAstroEventAccuracy: number; deepAstroCoverage: number; baselines: BaselineResult[]; improvementOverRandom: number | null; improvementOverDomainPrior: number | null; verdict: "BEATS_ALL_BASELINES" | "BEATS_RANDOM" | "NO_IMPROVEMENT" | "INSUFFICIENT_DATA"; sampleSize: number; computedAt: string; }
export interface CoverageMetrics { totalPredictions: number; testablePredictions: number; confirmedOutcomes: number; partialOutcomes: number; unknownOutcomes: number; suppressedPredictions: number; coverage: number; testableCoverage: number; precision: number | null; recall: number | null; suppressionRate: number; unknownRate: number; computedAt: string; }
export type HallucinationType = "FABRICATED_SOURCE" | "FAKE_CITATION" | "INVENTED_ASTRONOMICAL_FACT" | "INVENTED_HISTORICAL_EVENT" | "INVENTED_USER_FACT" | "UNSUPPORTED_STATISTIC" | "FALSE_CERTAINTY" | "FALSE_MODEL_CLAIM" | "NONE";
export type HallucinationSeverity = "CLEAN" | "LOW_RISK" | "HIGH_RISK" | "CRITICAL_QUALITY_FAILURE";
export interface HallucinationAuditResult { predictionId: string; detectedHallucinations: Array<{ type: HallucinationType; evidence: string; location: string; severity: "LOW" | "HIGH" | "CRITICAL"; }>; overallSeverity: HallucinationSeverity; auditedAt: string; auditNotes: string; }
export type PostHocStatus = "CLEAN" | "POST_HOC_REASONING_DETECTED" | "INSUFFICIENT_DATA";
export interface PostHocAnalysis { predictionId: string; originalForecastHash: string; postOutcomeExplanation?: string; newEvidenceIntroduced: string[]; status: PostHocStatus; excludedFromAccuracy: boolean; analyzedAt: string; }
export type DeduplicationStatus = "UNIQUE" | "DUPLICATE" | "OVERLAPPING" | "SUPERSEDED";
export interface DeduplicationResult { predictionId: string; status: DeduplicationStatus; duplicateOf?: string; overlapsWith: string[]; similarityScore: number; reason: string; }
export interface DomainCalibrationReport { domain: string; sampleSize: number; brierScore: number | null; eventAccuracy: number | null; timingAccuracy: number | null; status: "SUFFICIENT" | "INSUFFICIENT_SAMPLE"; computedAt: string; }
export type PredictionHorizon = "1M" | "3M" | "6M" | "1Y" | "3Y" | "5Y" | "10Y";
export interface TemporalCalibrationReport { horizon: PredictionHorizon; sampleSize: number; timingPrecision: number | null; outcomeRate: number | null; coverageRate: number | null; uncertaintyBand: number; status: "SUFFICIENT" | "INSUFFICIENT_SAMPLE"; computedAt: string; }
export interface ProviderPosition { provider: string; prediction: string; confidence: number; keyEvidence: string[]; recommendation: ChallengeRecommendation; }
export interface ProviderDisagreementResult { predictionId: string; providers: ProviderPosition[]; disagreementLevel: "NONE" | "MINOR" | "SIGNIFICANT" | "FUNDAMENTAL"; confidenceAdjustment: number; action: "NO_CHANGE" | "REDUCE_CONFIDENCE" | "SHOW_UNCERTAINTY" | "SUPPRESS"; recordedAt: string; }
export interface DisconfirmationMetrics { totalChallenged: number; weaknessesFound: number; softened: number; suppressed: number; contradicted: number; disconfirmationRate: number; healthStatus: "HEALTHY" | "SUSPICIOUSLY_CLEAN" | "OVER_CHALLENGED"; computedAt: string; }
export type KnowledgeVerificationStatus = "VERIFIED" | "PARTIALLY_VERIFIED" | "UNVERIFIED" | "CONTRADICTED" | "DEPRECATED";
export interface KnowledgeSourceRecord { sourceId: string; sourceType: "CLASSICAL_TEXT" | "RESEARCH" | "USER_OBSERVATION" | "AI_SYNTHESIS" | "CALCULATION" | "EXTERNAL_DB"; sourceVersion: string; retrievedAt: string; verificationStatus: KnowledgeVerificationStatus; evidenceHash: string; claimText: string; }
export interface ImmutablePredictionRecord { predictionId: string; contentHash: string; issuedAt: string; frozenFields: { text: string; claim: string; confidence: number; evidenceIds: string[]; calculationSnapshotHash: string; modelId: string; providerId: string; promptVersion: string; knowledgeVersion: string; engineVersion: string; }; appendedRecords: Array<{ type: "OUTCOME" | "EVALUATION" | "DIAGNOSIS" | "REVIEW"; data: Record<string, unknown>; appendedAt: string; appendedBy: string; }>; }
export type DatasetType = "SYNTHETIC_TEST_DATA" | "CALIBRATION_DATA" | "HISTORICAL_DATA" | "REAL_USER_OBSERVATIONS" | "EXTERNALLY_VERIFIED_OUTCOMES";
export interface DatasetRecord { datasetId: string; type: DatasetType; predictionIds: string[]; canContributeToRealWorldAccuracy: boolean; createdAt: string; }
export interface ModelPerformanceVector { providerId: string; evidence_adherence: number; unsupported_claim_rate: number; hallucination_rate: number; confidence_calibration: number; contradiction_rate: number; testability: number; timing_quality: number; event_match: number; latency_ms: number; token_consumption: number; failure_rate: number; json_reliability: number; sampleSize: number; computedAt: string; }
