/**
 * DeepAstro Public Report & Forecast Verification Route
 * Version: FORTRESS-1.0
 * Endpoint: /api/verify/report/:reportId
 * Allows third parties and clients to cryptographically verify if a report,
 * forecast, or reading was authentically generated by DeepAstro without
 * exposing private user identities, birth coordinates, or private context.
 */

import { Router, Request, Response } from 'express';
import { DeepAstroProvenanceService } from '../services/DeepAstroProvenanceService.js';

const router = Router();

// GET /api/verify/report/:reportId and /verify/report/:reportId
router.get('/report/:reportId', (req: Request, res: Response) => {
  const { reportId } = req.params;

  if (!reportId || typeof reportId !== 'string' || reportId.trim().length === 0) {
    return res.status(400).json({
      verified: false,
      error: 'INVALID_REPORT_ID',
      message: 'A non-empty report ID or verification identifier is required.',
    });
  }

  const result = DeepAstroProvenanceService.verifyReport(reportId.trim());

  if (!result.verified) {
    return res.status(404).json({
      verified: false,
      reportId: reportId.trim(),
      status: 'UNVERIFIED',
      message: 'No authentic DeepAstro certificate matches the provided verification identifier.',
    });
  }

  return res.json({
    verified: true,
    verificationId: result.verificationId,
    status: result.status,
    certificate: result.details,
    issuer: 'DeepAstro Autonomous Astrological Verification Authority',
    cryptographicStandard: 'SHA-256 / CANONICAL-JSON-V1',
    timestamp: new Date().toISOString(),
  });
});

export default router;
